name: Devin Halladay
url: http://devinhalladay.com
description: 'This is the personal journal and portfolio of Devin Halladay &mdash; a designer, developer, and writer.'

timezone: America/New_York
port: 4200

markdown: rdiscount
rdiscount:
  extensions:
    - smart
    - generate_toc

permalink: /journal/:title
paginate: 6

exclude: ['README.md', 'Rakefile', 'Gemfile', 'Gemfile.lock']

assets:
  js_compressor: uglifier
  css_compressor: sass
  sources:
    - _assets/fonts
    - _assets/js
    - _assets/sass
    - _assets/img
  gzip: false