name: Devin Halladay
url: http://devinhalladay.com
description: 'This is the portfolio and journal of Devin Halladay, a designer &amp; writer in Cleveland, Ohio.'

timezone: America/New_York
port: 4200

markdown: rdiscount
rdiscount:
  extensions:
    - smart
    - generate_toc

permalink: /:categories/:title
paginate: 6

exclude: ['README.md', 'Rakefile', 'Gemfile', 'Gemfile.lock']
include: ['.htaccess', 'keybase.txt']

assets:
  js_compressor: uglifier
  css_compressor: sass
  sources:
    - _assets/fonts
    - _assets/js
    - _assets/sass
  gzip: false