name: Devin Halladay
url: http://devinhalladay.com
description: 'This is the portfolio and journal of Devin Halladay, a designer &amp; writer in Cleveland, Ohio.'

timezone: America/New_York
port: 4200

markdown: rdiscount
rdiscount:
  extensions:
    - smart
    - generate_toc

permalink: /journal/:title
paginate: 6

collections:
  projects:
    output: true
    layout: default
    permalink: /projects/:path/

exclude: ['README.md', 'Rakefile', 'Gemfile', 'Gemfile.lock']
include: ['.htaccess', 'keybase.txt']

assets:
  js_compressor: uglifier
  css_compressor: sass
  sources:
    - _assets/fonts
    - _assets/js
    - _assets/sass
  gzip: false