- category: Print
  list:
  - Editorial Design
  - Posters
  - Business Cards

- category: Digital
  list:
  - Web Design
  - Web Development
  - Responsive Design
  - Web Typography

- category: Branding
  list:
  - Brand Creation
  - Logo Design
  - Identity Design
  - Brand Collateral
  - Brand Strategy


- category: Content Creation
  list:
  - Copywriting