- category: Print
  list:
  - Editorial Design
  - Typography
  - Posters
  - Business Cards

- category: Digital
  list:
  - 'Web Design &amp; Development'
  - Responsive Design
  - Web Typography

- category: Branding
  list:
  - Brand Creation
  - Logo Design
  - Identity Design
  - Brand Collateral
  - Custom Typography


- category: Content Creation
  list:
  - Copywriting
  - Illustration